eureka:
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      routes[0]:
        id: ACCOUNT-SERVICE
        uri: lb://ACCOUNT-SERVICE
        predicates[0]: Path=/account/**
      routes[1]:
        uri: lb://CUSTOMER-SERVICE
        id: CUSTOMER-SERVICE
        predicates[0]: Path=/customer/**
  application:
    name: api-gateway
server:
  port: '8999'
